name: Deploy Front Production

on:
  push:
    branches:
      - 'master'
env:
  BUCKET_NAME: ${{ secrets.S3_BUCKET }}
  AWS_REGION: ${{ secrets.AWS_DEFAULT_REGION }}
  AWS_ROLE_SESSION_NAME: ${{ secrets.AWS_ROLE_SESSION_NAME }}

permissions:
  id-token: write
  contents: write

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Setup Pages
        uses: actions/configure-pages@v5
      - name: Set up ruby
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: '2.5.0'
      - name: Install jekyll
        run: gem install jekyll bundler
      - name: Build site
        run: jekyll build
  deploy:
    needs: build
    runs-on: ubuntu-latest
    steps:
      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v2
        with:
          role-to-assume: ${{ env.AWS_ROLE_SESSION_NAME }}
          role-session-name: "GitHubActions"
          aws-region: ${{ env.AWS_REGION }}

      - name: Upload to S3
        run: aws s3 sync _site/ s3://${{ env.BUCKET_NAME }}

      - name: Invalidate CloudFront
        run: aws cloudfront create-invalidation --distribution-id ${{ secrets.CLOUDFRONT_DISTRIBUTION_ID }} --paths "/*"
