name: Deploy Front Production

on:
  push:
    branches:
      - 'master'
env:
  BUCKET_NAME: ${{ secrets.S3_BUCKET }}
  AWS_REGION: ${{ secrets.AWS_DEFAULT_REGION }}
  AWS_ROLE_SESSION_NAME: ${{ secrets.AWS_ROLE_SESSION_NAME }}

permissions:
  id-token: write
  contents: write

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:

      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up Ruby
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: 2.7

      - name: Install Jekyll and Bundler
        run: |
          gem install bundler
          bundle install

      - name: Build Jekyll site
        run: bundle exec jekyll build

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v2
        with:
          role-to-assume: ${{ env.AWS_ROLE_SESSION_NAME }}
          role-session-name: "GitHubActions"
          aws-region: ${{ env.AWS_REGION }}

      - name: Upload to S3
        run: aws s3 sync _site/ s3://${{ env.BUCKET_NAME }}

      - name: Invalidate CloudFront
        run: aws cloudfront create-invalidation --distribution-id ${{ secrets.CLOUDFRONT_DISTRIBUTION_ID }} --paths "/*"
